name: Linting and Unit tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Use Python version 3.7
      uses: actions/setup-python@v3
      with:
        python-version: '3.7'
    - name: Install Flake8
      run: |
        python -m pip install flake8
    - name: Run linting tests
      run: | 
        flake8 src/model/
    - name: Install Pytest
      run: |
        python -m pip install pytest
    - name: Install requirements for Unit tests
      run: |
        python -m pip install -r requirements.txt 
    - name: Run unit tests with Pytest
      run: |
        pytest tests/test_train.py 
