name: Trigger AML job

on:
  workflow_dispatch:
    # inputs:
    #   resource_group:
    #     description: 'Resource group name'
    #     required: true
    #     default: 'rg-mlopsv2jota-42prod' 
    #     type: string
    #   aml_workspace:
    #     description: 'Azure Machine Learning workspace name'
    #     required: true
    #     default: 'mlw-mlopsv2jota-42prod' 
    #     type: string
  push:
    branches:
      - 'main'
    paths:
      - '**.py'
      - '**.yml'

jobs:
  build:
    name: Trigger AML job
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Set defaults
      run: |
        az configure --defaults group=rg-mlopsv2jota-42prod workspace=mlw-mlopsv2jota-42prod location=northeurope
    - name: Create AML Job
      run: |
        az ml job create --file src/job.yml 
        # -g "${{ github.event.inputs.resource_group }}" -w "${{ github.event.inputs.aml_workspace}}"
        
