name: Train, Register and Deploy

on:
  workflow_dispatch:
    inputs:
      resource_group:
        description: 'Resource group name'
        required: true
        default: 'rg-mlopsv2jota-42prod' 
        type: string
      aml_workspace:
        description: 'Azure Machine Learning workspace name'
        required: true
        default: 'mlw-mlopsv2jota-42prod' 
        type: string

jobs:
  Train_Model:
    name: Train model
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Set defaults
      run: |
        az configure --defaults group="${{ github.event.inputs.resource_group }}" workspace="${{ github.event.inputs.aml_workspace}}" location=northeurope
    - name: Create AML Job
      run: |
        az ml job create --file src/job.yml 

  Register_Model:
    name: Register Model
    runs-on: ubuntu-latest
    needs: Train_Model
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Set defaults
      run: |
        az configure --defaults group="${{ github.event.inputs.resource_group }}" workspace="${{ github.event.inputs.aml_workspace}}" location=northeurope
    - name: Register model in AML
      run: |
        JOB_NAME=$(az ml job list --query "[0].name" | tr -d '"')
        az ml model create --name "diabetes-model" --type "mlflow_model" --path "azureml://jobs/$JOB_NAME/outputs/artifacts/model"

  Deploy_Model:
    name: Deploy model
    runs-on: ubuntu-latest
    needs: Register_Model
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Set defaults
      run: |
        az configure --defaults group="${{ github.event.inputs.resource_group }}" workspace="${{ github.event.inputs.aml_workspace}}" location=northeurope
    - name: Deploy to Managed Endpoint
      run: |
        az ml online-endpoint create --name "mlopsopenlab-diabetes-endpoint" -f ./src/endpoint-spec.yml
        az ml online-deployment create --name "mlopsopenlab-diabetes-deployment" -f ./src/deployment-spec.yml


